# Generated by Django 4.2.7 on 2023-12-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_message_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('cancelled', 'cancelled'), ('shipped', 'shipped'), ('pending', 'pending')], default='pending', max_length=50),
        ),
    ]
