# Generated by Django 4.2.7 on 2023-12-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='mobile_numbers',
        ),
        migrations.AddField(
            model_name='orders',
            name='mobile_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('cancelled', 'cancelled'), ('pending', 'pending'), ('shipped', 'shipped')], default='pending', max_length=50),
        ),
    ]
